language: node_js
cache:
  yarn: true
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '9'
  - '8'
  - '6'
  - '4'
install:
  - yarn global add codecov typescript
  - yarn
script:
  - yarn run lint
  - yarn run test
  - codecov
after_success:
  - yarn run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
